import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "./providers/i18nProvider";
import { ThemeProvider } from "./providers/ThemeProvider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${poppins.className} antialiased`}
      >
        <I18nProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >{children}</ThemeProvider></I18nProvider>
      </body>
    </html>
  );
}
